version: "3"

services:
  mysql_db_1:
    image: mysql:8.0.30
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=fleetman1
    volumes:
      - fleetman1:/var/lib/mysql
  mysql_db_2:
    image: mysql:8.0.30
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=fleetman2
    volumes:
      - fleetman2:/var/lib/mysql

volumes:
  fleetman1:
  fleetman2: